Repository OrcaBus/service-workflow-manager, pull requests merged in 2025-08, with the labels that each got.

#45 Bumped dependencies
  package.json
  pnpm-lock.yaml
  pnpm-workspace.yaml
Labels: dependencies

#44 Fixed sim_analysis execution engine AWS_BATCH
  app/workflow_manager/tests/fixtures/sim_analysis.py
  package.json
  pnpm-lock.yaml
  pnpm-workspace.yaml
Labels: fix

#46 Made workflow API endpoint post only
  app/workflow_manager/migrations/0008_alter_workflow_execution_engine_and_more.py
  app/workflow_manager/models/workflow.py
  app/workflow_manager/serializers/workflow.py
  app/workflow_manager/viewsets/base.py
  app/workflow_manager/viewsets/workflow.py
Labels: enhancement

#51 Aru event schema
  docs/events/AnalysisRunUpdate/AnalysisRunUpdate.schema.yaml
  docs/events/AnalysisRunUpdate/examples/ARU__example_DRAFT.json
  docs/events/AnalysisRunUpdate/examples/ARU__example_READY.json
Labels: enhancement

#53 Generated AnalysisRunUpdate.schema.json
  docs/events/AnalysisRunUpdate/AnalysisRunUpdate.schema.json
  docs/events/Makefile
  docs/events/README.md
Labels: documentation

#54 Generated AnalysisRunUpdate and WorkflowRunUpdate pydantic domain models
  app/Makefile
  app/workflow_manager_proc/domain/event/aru.py
  app/workflow_manager_proc/domain/event/wru.py
Labels: enhancement

#57 Deprecated AnalysisRunInitiated.schema.json AnalysisRunFinalised.schema.json
  app/Makefile
  app/workflow_manager_proc/domain/event/arf.py
  app/workflow_manager_proc/domain/event/ari.py
  app/workflow_manager_proc/lambdas/handle_analysis_run_finalised_event.py
  app/workflow_manager_proc/lambdas/handle_analysis_run_initiated_event.py
  app/workflow_manager_proc/tests/case.py
  app/workflow_manager_proc/tests/fixtures/ARF_event_1.json
  app/workflow_manager_proc/tests/fixtures/ARI_event_1.json
  app/workflow_manager_proc/tests/fixtures/ARU_draft_max.json
  app/workflow_manager_proc/tests/fixtures/ARU_draft_min.json
  app/workflow_manager_proc/tests/fixtures/ARU_ready_max.json
  app/workflow_manager_proc/tests/fixtures/ARU_ready_min.json
  app/workflow_manager_proc/tests/test_analysis_run.py
  docs/events/AnalysisRunFinalised/AnalysisRunFinalised.schema.json
  docs/events/AnalysisRunFinalised/AnalysisRunFinalised.schema.yaml
  docs/events/AnalysisRunFinalised/examples/ARF__example.json
  docs/events/AnalysisRunInitiated/AnalysisRunInitiated.schema.json
  docs/events/AnalysisRunInitiated/AnalysisRunInitiated.schema.yaml
  docs/events/AnalysisRunInitiated/examples/ARI__example1.json
Labels: enhancement, refactor

#58 Docs update
  README.md
  app/workflow_manager/models/workflow.py
  docs/diagrams/workflow-manager-entity-diagram.drawio.svg
Labels: documentation

#59 Entity diagram fix
  .pre-commit-config.yaml
  .prettierignore
  docs/diagrams/workflow-manager-entity-diagram.drawio.svg
Labels: documentation

#68 Update entity model
  docs/diagrams/workflow-manager-entity-diagram.drawio.svg
Labels: documentation, enhancement

#75 Implemented RunContext model
  app/workflow_manager/migrations/0013_remove_analysisrun_contexts_and_more.py
  app/workflow_manager/migrations/0014_runcontext_analysisrun_contexts_workflowrun_contexts.py
  app/workflow_manager/migrations/0015_alter_analysiscontext_usecase.py
  app/workflow_manager/models/__init__.py
  app/workflow_manager/models/analysis_context.py
  app/workflow_manager/models/analysis_run.py
  app/workflow_manager/models/run_context.py
  app/workflow_manager/models/workflow_run.py
  app/workflow_manager/models/workflow_run_context.py
  app/workflow_manager/serializers/run_context.py
  app/workflow_manager/serializers/workflow_run_context.py
  app/workflow_manager/tests/fixtures/sim_analysis.py
  app/workflow_manager/tests/test_models.py
  app/workflow_manager/urls/base.py
  app/workflow_manager/viewsets/analysis_run_context.py
  app/workflow_manager/viewsets/run_context.py
  app/workflow_manager/viewsets/workflow_run_context.py
  app/workflow_manager_proc/services/analysis_run.py
  app/workflow_manager_proc/tests/test_analysis_run.py
Labels: enhancement

#78 Generated WRSC and WRU domain event pydantic models
  app/workflow_manager_proc/domain/event/wrsc.py
  app/workflow_manager_proc/domain/event/wru.py
Labels: enhancement

#85 Update WRU event schema
  docs/events/WorkflowRunUpdate/WorkflowRunUpdate.schema.json
  docs/events/WorkflowRunUpdate/WorkflowRunUpdate.schema.yaml
Labels: documentation

#87 Implemented WorkflowManager Schema Registry
  infrastructure/stage/schema.ts
  infrastructure/stage/stack.ts
  test/schema.test.ts
Labels: enhancement

#88 Opt-out CDK CLI telemetry
  cdk.context.json
  cdk.json
Labels: devops

#90 Improved EventBridge Registry CDK components deployment dependency
  infrastructure/stage/schema.ts
Labels: enhancement, fix

#91 Update AnalysisRun DB to ARSC mapping
  app/workflow_manager_proc/services/analysis_run.py
  app/workflow_manager_proc/tests/test_analysis_run.py
Labels: enhancement

#92 Fixed CDK deploy schema registryName
  infrastructure/stage/schema.ts
Labels: fix

#93 Improved Readset and RunContext linking to WorkflowRun
  app/workflow_manager_proc/services/workflow_run.py
  app/workflow_manager_proc/tests/test_workflow_run.py
Labels: enhancement, fix

#101 Added Workflow codeVersion property to WRSC and WRU event schema
  docs/events/WorkflowRunStateChange/WorkflowRunStateChange.schema.yaml
  docs/events/WorkflowRunUpdate/WorkflowRunUpdate.schema.yaml
Labels: enhancement, change request

#104 Made Workflow API endpoint executionEnginePipelineId optional
  app/workflow_manager/migrations/0018_alter_workflow_execution_engine_pipeline_id.py
  app/workflow_manager/models/workflow.py
Labels: enhancement, change request

#103 Updated code changes for WRSC WRU Workflow new properties
  app/workflow_manager/migrations/0018_alter_workflow_execution_engine_pipeline_id.py
  app/workflow_manager/models/workflow.py
  app/workflow_manager/tests/factories.py
  app/workflow_manager_proc/domain/event/wrsc.py
  app/workflow_manager_proc/domain/event/wru.py
  app/workflow_manager_proc/services/workflow_run.py
  app/workflow_manager_proc/services/workflow_run_legacy.py
  app/workflow_manager_proc/tests/fixtures/WRU_max.json
  app/workflow_manager_proc/tests/fixtures/WRU_min.json
  app/workflow_manager_proc/tests/test_handle_wru_event.py
  app/workflow_manager_proc/tests/test_workflow_run.py
  docs/events/WorkflowRunStateChange/WorkflowRunStateChange.schema.json
  docs/events/WorkflowRunStateChange/examples/WRSC__example1.json
  docs/events/WorkflowRunStateChange/examples/WRSC__example2.json
  docs/events/WorkflowRunUpdate/WorkflowRunUpdate.schema.json
  docs/events/WorkflowRunUpdate/examples/WRU__example1.json
  docs/events/WorkflowRunUpdate/examples/WRU__example2.json
  docs/events/WorkflowRunUpdate/examples/WRU__example3.json
Labels: enhancement, change request
